# ***pytorch fundamentals - oo***

In [1]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# introducing to tensor

Creating tensors


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor((7,7))
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random Tensors

In [17]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7327, 0.3789, 0.0718, 0.8247],
        [0.3418, 0.0731, 0.2028, 0.8933],
        [0.8903, 0.4789, 0.0669, 0.1500]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.5316, 0.2314, 0.8860, 0.2825, 0.4381, 0.9029, 0.5740, 0.3578, 0.4736,
         0.0871],
        [0.6084, 0.9336, 0.6725, 0.4953, 0.5549, 0.2728, 0.9749, 0.9591, 0.0399,
         0.5139],
        [0.2278, 0.6496, 0.1093, 0.4541, 0.8864, 0.4024, 0.4326, 0.5217, 0.0713,
         0.6808],
        [0.9899, 0.5884, 0.0895, 0.3250, 0.5331, 0.9609, 0.0649, 0.0497, 0.5327,
         0.1184],
        [0.7816, 0.3488, 0.5501, 0.1827, 0.6163, 0.0073, 0.3627, 0.2074, 0.6554,
         0.3767],
        [0.1867, 0.9794, 0.5571, 0.7431, 0.8572, 0.0345, 0.8957, 0.0119, 0.8631,
         0.5558],
        [0.1487, 0.6011, 0.5200, 0.5719, 0.3120, 0.3453, 0.2046, 0.0119, 0.1001,
         0.2301],
        [0.8835, 0.8524, 0.1038, 0.8436, 0.1585, 0.9363, 0.9963, 0.7149, 0.8852,
         0.8908],
        [0.3138, 0.3850, 0.3966, 0.9444, 0.4988, 0.3008, 0.6456, 0.7160, 0.4366,
         0.2923],
        [0.7675, 0.9402, 0.3262, 0.2759, 0.2079, 0.0781, 0.8097, 0.6621, 0.3945,
         0.5294]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[5.4053e-01, 7.2600e-01, 6.9729e-01, 6.0579e-01, 8.1719e-01,
          8.2582e-04, 3.5428e-01, 6.9173e-01, 4.9896e-01, 2.2580e-01],
         [8.1263e-01, 3.6237e-01, 5.5205e-01, 5.7550e-01, 8.5648e-01,
          1.3859e-02, 8.1099e-01, 5.9434e-01, 7.3430e-01, 8.3788e-01],
         [2.0760e-01, 7.5221e-01, 7.3409e-01, 2.2141e-01, 5.4138e-02,
          2.7779e-01, 5.2288e-01, 5.0246e-01, 6.4391e-02, 8.2053e-02],
         [4.1699e-01, 5.2771e-01, 2.8980e-01, 9.0230e-02, 5.0581e-01,
          7.0175e-01, 1.0660e-01, 4.6106e-01, 9.4736e-01, 1.7881e-01],
         [4.5565e-01, 4.3046e-01, 6.6390e-01, 7.2740e-01, 3.5312e-01,
          3.7436e-01, 6.5833e-01, 1.4867e-01, 4.0009e-01, 2.5098e-01],
         [3.6621e-01, 9.6800e-01, 2.0688e-01, 1.9202e-01, 6.9356e-01,
          7.6515e-01, 1.1023e-01, 9.5611e-01, 5.3901e-01, 6.8776e-01],
         [4.8614e-01, 7.4007e-01, 1.8411e-01, 8.0001e-01, 1.1711e-02,
          7.7923e-01, 1.2322e-01, 9.2683e-01, 8.8451e-01, 7.8467e-01],
         [8.8

In [22]:
random_tensor.ndim

3

In [23]:
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[9.8080e-01, 7.3176e-01, 7.0829e-01, 6.0600e-02, 2.5879e-02,
          9.0244e-01, 9.7349e-01, 9.0289e-01, 2.9028e-01, 5.6741e-01],
         [6.9501e-01, 4.2909e-01, 7.9129e-02, 4.0178e-01, 2.3974e-01,
          7.4398e-01, 9.6963e-01, 5.3587e-01, 4.4382e-01, 9.7409e-01],
         [7.3274e-01, 6.1564e-01, 4.6717e-01, 8.2858e-02, 6.6932e-02,
          4.6677e-01, 3.0486e-01, 1.1962e-02, 5.1637e-01, 4.5351e-01],
         [4.7977e-01, 6.9983e-01, 4.1219e-01, 1.1673e-01, 8.6054e-01,
          7.8967e-01, 4.1202e-02, 9.8791e-02, 7.1065e-02, 5.9931e-01],
         [5.1142e-01, 4.1775e-01, 1.8609e-04, 6.6036e-01, 1.8815e-01,
          4.0734e-01, 2.6676e-01, 4.9335e-01, 4.4886e-01, 9.1437e-01],
         [7.9891e-02, 6.1586e-01, 7.1378e-01, 2.1632e-01, 8.5521e-01,
          1.9024e-01, 6.0955e-01, 7.7439e-01, 9.9605e-01, 4.6973e-01],
         [3.7124e-01, 5.9717e-01, 9.8462e-01, 7.1539e-01, 3.3399e-01,
          8.4795e-01, 9.0043e-01, 3.0450e-01, 7.4922e-01, 7.8529e-01],
         [7.5

In [24]:
random_tensor.ndim

3

In [27]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width,color channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)